
/*
声明式流水线
*/

pipeline {
	agent any
	stages {
		stage('Build'){
			/* 
			定义环境变量:
			
			*/
			environment { 
      	M2_HOME=/home/boco/apache-maven-3.6.3      	
      }
			steps{
				echo "拉取代码"
				checkout changelog: false, scm: [$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'demoproj', url: 'http://39.101.173.235:9843/DW/demo-oss4-oms-vue.git']]]					
				
				echo "项目位置:${env.$WORKSPACE}"
				echo "编译后端"
				sh "cd /home/boco/jenkins/workspace/demo1"
    		sh "${M2_HOME}/bin/mvn clean package"
			}
		}
	}
}