
/*
声明式流水线
*/

pipeline {
	agent any
	stages {
		stage('Build'){
			/*
			定义环境变量:
			*/
			environment {
      	M2_HOME = "/home/boco/apache-maven-3.6.3"
      	BACKEND_HOME= "/home/boco/jenkins/workspace/demo1/oss4-oms"
      	NODE_HOME="/home/boco/node-v12.16.3-linux-x64"
      }
			steps{
				echo "拉取代码"

				// checkout changelog: false, scm: [$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'demoproj', url: 'http://39.101.173.235:9843/DW/demo-oss4-oms-vue.git']]]



				echo "项目位置:${env.$WORKSPACE},构建号:${env.BUILD_NUMBER},项目名称:${env.JOB_NAME}"
				echo "编译后端"
				dir('oss4-oms') {
    			// sh "${M2_HOME}/bin/mvn clean package"
    		}	// end dir('oss4-oms')

				echo "编译前端"
				dir('oss4-oms-ui') {
            	// sh '${NODE_HOME}/bin/npm install'
            	// sh "${NODE_HOME}/bin/npm run build:prod"
				} // end dir('oss4-oms-ui')
				
				echo "编译完成"
			} //end steps
			
			
		} // end stage('Build')
		stage('Deploy'){
			environment {
				SRC_BACKEND_FILE="dw-admin/target/dw-admin.jar"
				SRC_FRONTEND_DIR="dist"
				DEST_DIR="/home/boco/daiwei_project"
				PRJ_BACKEND_DIR="backend"
				PRJ_FRONTEND_DIR="frontend"
			}
			steps{
				echo "开始部署"
				
				dir('oss4-oms') {
					echo "拷贝后端JAR到${DEST_DIR}/${PRJ_BACKEND_DIR}目录"
					sh "cp -p ${SRC_BACKEND_FILE} ${DEST_DIR}/${PRJ_BACKEND_DIR}/"
				} //end dir('oss4-oms')
				
				dir('oss4-oms-ui') {
					echo "拷贝后端目录到${DEST_DIR}/${PRJ_FRONTEND_DIR}目录"
					sh "cp -pr ${SRC_FRONTEND_DIR} ${DEST_DIR}/${PRJ_FRONTEND_DIR}/"
				} //end dir('oss4-oms-ui')
				
				echo "部署完毕"
			}
		}
	}
}